### ISSUE TITLE
glibc issue with latest version

### ISSUE THREAD

**Issue by Nedyaz** [YPSI-SAS/centctl#28]
**Describe the bug**

I'm trying to use cenctl on RHEL 7 servers,

When I try to run cenctl I get the following error : 
```
./centctl: /lib64/libc.so.6: version 'GLIBC_2.32' not found (required by ./centctl)
./centctl: /lib64/libc.so.6: version 'GLIBC_2.34' not found (required by ./centctl)
```

**To Reproduce**
simply try to use centctl

**Expected behavior**
I was expecting cenctl to work normally

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: RHEL 7.9
 - Version : Centctl latest version

**Comment by vcoumailleau** [comment]
Hello,
We are working on a fix, but for now you can try to build centctl from sources directly on your RHEL7 server

You will need to install git and go on your RHEL 7 server
```
sudo yum install git go
git clone https://github.com/YPSI-SAS/centctl.git
cd centctl
go build
```

And then try the generated binary
`./centctl --server YOUR_SERVER list host`

If it works, you can copy the generated binary to your other RHEL7 servers to use it

We will let you know when the fix is out

Regards

**Comment by vcoumailleau** [comment]
Hello,
Can you try the  pre-release V2.5.9, with the binary centctl_linux_woc_amd64?

Regards
